sudo: false

os:
 - linux

language: node_js
dist: bionic
services:
  - xvfb

node_js:
  - 12

env:
  - CODE_VERSION=latest

install:
  - npm install
  - npm run build

before_script:
  - npm run prepare-test

script:
  - npm run ci-test
